// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/apoxy-dev/apoxy-cli/api/controllers/v1alpha1"
	scheme "github.com/apoxy-dev/apoxy-cli/client/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ProxyDeploymentsGetter has a method to return a ProxyDeploymentInterface.
// A group's client should implement this interface.
type ProxyDeploymentsGetter interface {
	ProxyDeployments() ProxyDeploymentInterface
}

// ProxyDeploymentInterface has methods to work with ProxyDeployment resources.
type ProxyDeploymentInterface interface {
	Create(ctx context.Context, proxyDeployment *v1alpha1.ProxyDeployment, opts v1.CreateOptions) (*v1alpha1.ProxyDeployment, error)
	Update(ctx context.Context, proxyDeployment *v1alpha1.ProxyDeployment, opts v1.UpdateOptions) (*v1alpha1.ProxyDeployment, error)
	UpdateStatus(ctx context.Context, proxyDeployment *v1alpha1.ProxyDeployment, opts v1.UpdateOptions) (*v1alpha1.ProxyDeployment, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ProxyDeployment, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ProxyDeploymentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProxyDeployment, err error)
	ProxyDeploymentExpansion
}

// proxyDeployments implements ProxyDeploymentInterface
type proxyDeployments struct {
	client rest.Interface
}

// newProxyDeployments returns a ProxyDeployments
func newProxyDeployments(c *ControllersV1alpha1Client) *proxyDeployments {
	return &proxyDeployments{
		client: c.RESTClient(),
	}
}

// Get takes name of the proxyDeployment, and returns the corresponding proxyDeployment object, and an error if there is any.
func (c *proxyDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProxyDeployment, err error) {
	result = &v1alpha1.ProxyDeployment{}
	err = c.client.Get().
		Resource("proxydeployments").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ProxyDeployments that match those selectors.
func (c *proxyDeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProxyDeploymentList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ProxyDeploymentList{}
	err = c.client.Get().
		Resource("proxydeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested proxyDeployments.
func (c *proxyDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("proxydeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a proxyDeployment and creates it.  Returns the server's representation of the proxyDeployment, and an error, if there is any.
func (c *proxyDeployments) Create(ctx context.Context, proxyDeployment *v1alpha1.ProxyDeployment, opts v1.CreateOptions) (result *v1alpha1.ProxyDeployment, err error) {
	result = &v1alpha1.ProxyDeployment{}
	err = c.client.Post().
		Resource("proxydeployments").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(proxyDeployment).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a proxyDeployment and updates it. Returns the server's representation of the proxyDeployment, and an error, if there is any.
func (c *proxyDeployments) Update(ctx context.Context, proxyDeployment *v1alpha1.ProxyDeployment, opts v1.UpdateOptions) (result *v1alpha1.ProxyDeployment, err error) {
	result = &v1alpha1.ProxyDeployment{}
	err = c.client.Put().
		Resource("proxydeployments").
		Name(proxyDeployment.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(proxyDeployment).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *proxyDeployments) UpdateStatus(ctx context.Context, proxyDeployment *v1alpha1.ProxyDeployment, opts v1.UpdateOptions) (result *v1alpha1.ProxyDeployment, err error) {
	result = &v1alpha1.ProxyDeployment{}
	err = c.client.Put().
		Resource("proxydeployments").
		Name(proxyDeployment.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(proxyDeployment).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the proxyDeployment and deletes it. Returns an error if one occurs.
func (c *proxyDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("proxydeployments").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *proxyDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("proxydeployments").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched proxyDeployment.
func (c *proxyDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProxyDeployment, err error) {
	result = &v1alpha1.ProxyDeployment{}
	err = c.client.Patch(pt).
		Resource("proxydeployments").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
