// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apoxy-dev/apoxy-cli/api/controllers/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ProxyDeploymentLister helps list ProxyDeployments.
// All objects returned here must be treated as read-only.
type ProxyDeploymentLister interface {
	// List lists all ProxyDeployments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ProxyDeployment, err error)
	// Get retrieves the ProxyDeployment from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ProxyDeployment, error)
	ProxyDeploymentListerExpansion
}

// proxyDeploymentLister implements the ProxyDeploymentLister interface.
type proxyDeploymentLister struct {
	indexer cache.Indexer
}

// NewProxyDeploymentLister returns a new ProxyDeploymentLister.
func NewProxyDeploymentLister(indexer cache.Indexer) ProxyDeploymentLister {
	return &proxyDeploymentLister{indexer: indexer}
}

// List lists all ProxyDeployments in the indexer.
func (s *proxyDeploymentLister) List(selector labels.Selector) (ret []*v1alpha1.ProxyDeployment, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ProxyDeployment))
	})
	return ret, err
}

// Get retrieves the ProxyDeployment from the index for a given name.
func (s *proxyDeploymentLister) Get(name string) (*v1alpha1.ProxyDeployment, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("proxydeployment"), name)
	}
	return obj.(*v1alpha1.ProxyDeployment), nil
}
