// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apoxy-dev/apoxy-cli/api/controllers/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ProxySetLister helps list ProxySets.
// All objects returned here must be treated as read-only.
type ProxySetLister interface {
	// List lists all ProxySets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ProxySet, err error)
	// Get retrieves the ProxySet from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ProxySet, error)
	ProxySetListerExpansion
}

// proxySetLister implements the ProxySetLister interface.
type proxySetLister struct {
	indexer cache.Indexer
}

// NewProxySetLister returns a new ProxySetLister.
func NewProxySetLister(indexer cache.Indexer) ProxySetLister {
	return &proxySetLister{indexer: indexer}
}

// List lists all ProxySets in the indexer.
func (s *proxySetLister) List(selector labels.Selector) (ret []*v1alpha1.ProxySet, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ProxySet))
	})
	return ret, err
}

// Get retrieves the ProxySet from the index for a given name.
func (s *proxySetLister) Get(name string) (*v1alpha1.ProxySet, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("proxyset"), name)
	}
	return obj.(*v1alpha1.ProxySet), nil
}
