// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

import (
	v1alpha "github.com/apoxy-dev/apoxy-cli/api/core/v1alpha"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AddressLister helps list Addresses.
// All objects returned here must be treated as read-only.
type AddressLister interface {
	// List lists all Addresses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha.Address, err error)
	// Get retrieves the Address from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha.Address, error)
	AddressListerExpansion
}

// addressLister implements the AddressLister interface.
type addressLister struct {
	indexer cache.Indexer
}

// NewAddressLister returns a new AddressLister.
func NewAddressLister(indexer cache.Indexer) AddressLister {
	return &addressLister{indexer: indexer}
}

// List lists all Addresses in the indexer.
func (s *addressLister) List(selector labels.Selector) (ret []*v1alpha.Address, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha.Address))
	})
	return ret, err
}

// Get retrieves the Address from the index for a given name.
func (s *addressLister) Get(name string) (*v1alpha.Address, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha.Resource("address"), name)
	}
	return obj.(*v1alpha.Address), nil
}
