/*
Copyright 2025 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

// AddressListerExpansion allows custom methods to be added to
// AddressLister.
type AddressListerExpansion interface{}

// BackendListerExpansion allows custom methods to be added to
// BackendLister.
type BackendListerExpansion interface{}

// DomainListerExpansion allows custom methods to be added to
// DomainLister.
type DomainListerExpansion interface{}

// DomainZoneListerExpansion allows custom methods to be added to
// DomainZoneLister.
type DomainZoneListerExpansion interface{}

// ProxyListerExpansion allows custom methods to be added to
// ProxyLister.
type ProxyListerExpansion interface{}

// TunnelNodeListerExpansion allows custom methods to be added to
// TunnelNodeLister.
type TunnelNodeListerExpansion interface{}

// TunnelPeerOfferListerExpansion allows custom methods to be added to
// TunnelPeerOfferLister.
type TunnelPeerOfferListerExpansion interface{}
