// Code generated by lister-gen. DO NOT EDIT.

package v1alpha

// AddressListerExpansion allows custom methods to be added to
// AddressLister.
type AddressListerExpansion interface{}

// BackendListerExpansion allows custom methods to be added to
// BackendLister.
type BackendListerExpansion interface{}

// DomainListerExpansion allows custom methods to be added to
// DomainLister.
type DomainListerExpansion interface{}

// ProxyListerExpansion allows custom methods to be added to
// ProxyLister.
type ProxyListerExpansion interface{}

// TunnelNodeListerExpansion allows custom methods to be added to
// TunnelNodeLister.
type TunnelNodeListerExpansion interface{}
