// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/apoxy-dev/apoxy-cli/client/versioned/typed/gateway/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeGatewayV1 struct {
	*testing.Fake
}

func (c *FakeGatewayV1) GRPCRoutes() v1.GRPCRouteInterface {
	return &FakeGRPCRoutes{c}
}

func (c *FakeGatewayV1) Gateways() v1.GatewayInterface {
	return &FakeGateways{c}
}

func (c *FakeGatewayV1) GatewayClasses() v1.GatewayClassInterface {
	return &FakeGatewayClasses{c}
}

func (c *FakeGatewayV1) HTTPRoutes() v1.HTTPRouteInterface {
	return &FakeHTTPRoutes{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeGatewayV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
