/*
Copyright 2024 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/apoxy-dev/apoxy-cli/api/extensions/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// EdgeFunctionLister helps list EdgeFunctions.
// All objects returned here must be treated as read-only.
type EdgeFunctionLister interface {
	// List lists all EdgeFunctions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.EdgeFunction, err error)
	// Get retrieves the EdgeFunction from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha2.EdgeFunction, error)
	EdgeFunctionListerExpansion
}

// edgeFunctionLister implements the EdgeFunctionLister interface.
type edgeFunctionLister struct {
	indexer cache.Indexer
}

// NewEdgeFunctionLister returns a new EdgeFunctionLister.
func NewEdgeFunctionLister(indexer cache.Indexer) EdgeFunctionLister {
	return &edgeFunctionLister{indexer: indexer}
}

// List lists all EdgeFunctions in the indexer.
func (s *edgeFunctionLister) List(selector labels.Selector) (ret []*v1alpha2.EdgeFunction, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.EdgeFunction))
	})
	return ret, err
}

// Get retrieves the EdgeFunction from the index for a given name.
func (s *edgeFunctionLister) Get(name string) (*v1alpha2.EdgeFunction, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("edgefunction"), name)
	}
	return obj.(*v1alpha2.EdgeFunction), nil
}
