// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/apoxy-dev/apoxy-cli/client/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Proxies returns a ProxyInformer.
	Proxies() ProxyInformer
	// ProxyDeployments returns a ProxyDeploymentInformer.
	ProxyDeployments() ProxyDeploymentInformer
	// ProxySets returns a ProxySetInformer.
	ProxySets() ProxySetInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Proxies returns a ProxyInformer.
func (v *version) Proxies() ProxyInformer {
	return &proxyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ProxyDeployments returns a ProxyDeploymentInformer.
func (v *version) ProxyDeployments() ProxyDeploymentInformer {
	return &proxyDeploymentInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// ProxySets returns a ProxySetInformer.
func (v *version) ProxySets() ProxySetInformer {
	return &proxySetInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
