// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/apoxy-dev/apoxy-cli/api/controllers/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProxySets implements ProxySetInterface
type FakeProxySets struct {
	Fake *FakeControllersV1alpha1
}

var proxysetsResource = v1alpha1.SchemeGroupVersion.WithResource("proxysets")

var proxysetsKind = v1alpha1.SchemeGroupVersion.WithKind("ProxySet")

// Get takes name of the proxySet, and returns the corresponding proxySet object, and an error if there is any.
func (c *FakeProxySets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProxySet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(proxysetsResource, name), &v1alpha1.ProxySet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySet), err
}

// List takes label and field selectors, and returns the list of ProxySets that match those selectors.
func (c *FakeProxySets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProxySetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(proxysetsResource, proxysetsKind, opts), &v1alpha1.ProxySetList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProxySetList{ListMeta: obj.(*v1alpha1.ProxySetList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProxySetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested proxySets.
func (c *FakeProxySets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(proxysetsResource, opts))
}

// Create takes the representation of a proxySet and creates it.  Returns the server's representation of the proxySet, and an error, if there is any.
func (c *FakeProxySets) Create(ctx context.Context, proxySet *v1alpha1.ProxySet, opts v1.CreateOptions) (result *v1alpha1.ProxySet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(proxysetsResource, proxySet), &v1alpha1.ProxySet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySet), err
}

// Update takes the representation of a proxySet and updates it. Returns the server's representation of the proxySet, and an error, if there is any.
func (c *FakeProxySets) Update(ctx context.Context, proxySet *v1alpha1.ProxySet, opts v1.UpdateOptions) (result *v1alpha1.ProxySet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(proxysetsResource, proxySet), &v1alpha1.ProxySet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProxySets) UpdateStatus(ctx context.Context, proxySet *v1alpha1.ProxySet, opts v1.UpdateOptions) (*v1alpha1.ProxySet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(proxysetsResource, "status", proxySet), &v1alpha1.ProxySet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySet), err
}

// Delete takes name of the proxySet and deletes it. Returns an error if one occurs.
func (c *FakeProxySets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(proxysetsResource, name, opts), &v1alpha1.ProxySet{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProxySets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(proxysetsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProxySetList{})
	return err
}

// Patch applies the patch and returns the patched proxySet.
func (c *FakeProxySets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProxySet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(proxysetsResource, name, pt, data, subresources...), &v1alpha1.ProxySet{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxySet), err
}
