// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/apoxy-dev/apoxy-cli/api/controllers/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeProxyDeployments implements ProxyDeploymentInterface
type FakeProxyDeployments struct {
	Fake *FakeControllersV1alpha1
}

var proxydeploymentsResource = v1alpha1.SchemeGroupVersion.WithResource("proxydeployments")

var proxydeploymentsKind = v1alpha1.SchemeGroupVersion.WithKind("ProxyDeployment")

// Get takes name of the proxyDeployment, and returns the corresponding proxyDeployment object, and an error if there is any.
func (c *FakeProxyDeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ProxyDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(proxydeploymentsResource, name), &v1alpha1.ProxyDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyDeployment), err
}

// List takes label and field selectors, and returns the list of ProxyDeployments that match those selectors.
func (c *FakeProxyDeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ProxyDeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(proxydeploymentsResource, proxydeploymentsKind, opts), &v1alpha1.ProxyDeploymentList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ProxyDeploymentList{ListMeta: obj.(*v1alpha1.ProxyDeploymentList).ListMeta}
	for _, item := range obj.(*v1alpha1.ProxyDeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested proxyDeployments.
func (c *FakeProxyDeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(proxydeploymentsResource, opts))
}

// Create takes the representation of a proxyDeployment and creates it.  Returns the server's representation of the proxyDeployment, and an error, if there is any.
func (c *FakeProxyDeployments) Create(ctx context.Context, proxyDeployment *v1alpha1.ProxyDeployment, opts v1.CreateOptions) (result *v1alpha1.ProxyDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(proxydeploymentsResource, proxyDeployment), &v1alpha1.ProxyDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyDeployment), err
}

// Update takes the representation of a proxyDeployment and updates it. Returns the server's representation of the proxyDeployment, and an error, if there is any.
func (c *FakeProxyDeployments) Update(ctx context.Context, proxyDeployment *v1alpha1.ProxyDeployment, opts v1.UpdateOptions) (result *v1alpha1.ProxyDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(proxydeploymentsResource, proxyDeployment), &v1alpha1.ProxyDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyDeployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeProxyDeployments) UpdateStatus(ctx context.Context, proxyDeployment *v1alpha1.ProxyDeployment, opts v1.UpdateOptions) (*v1alpha1.ProxyDeployment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(proxydeploymentsResource, "status", proxyDeployment), &v1alpha1.ProxyDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyDeployment), err
}

// Delete takes name of the proxyDeployment and deletes it. Returns an error if one occurs.
func (c *FakeProxyDeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(proxydeploymentsResource, name, opts), &v1alpha1.ProxyDeployment{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeProxyDeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(proxydeploymentsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ProxyDeploymentList{})
	return err
}

// Patch applies the patch and returns the patched proxyDeployment.
func (c *FakeProxyDeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ProxyDeployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(proxydeploymentsResource, name, pt, data, subresources...), &v1alpha1.ProxyDeployment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ProxyDeployment), err
}
