// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apoxy-dev/apoxy-cli/client/versioned/typed/controllers/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeControllersV1alpha1 struct {
	*testing.Fake
}

func (c *FakeControllersV1alpha1) Proxies() v1alpha1.ProxyInterface {
	return &FakeProxies{c}
}

func (c *FakeControllersV1alpha1) ProxyDeployments() v1alpha1.ProxyDeploymentInterface {
	return &FakeProxyDeployments{c}
}

func (c *FakeControllersV1alpha1) ProxySets() v1alpha1.ProxySetInterface {
	return &FakeProxySets{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeControllersV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
