//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeFunction) DeepCopyInto(out *EdgeFunction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeFunction.
func (in *EdgeFunction) DeepCopy() *EdgeFunction {
	if in == nil {
		return nil
	}
	out := new(EdgeFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeFunction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeFunctionCodeSource) DeepCopyInto(out *EdgeFunctionCodeSource) {
	*out = *in
	if in.JsSource != nil {
		in, out := &in.JsSource, &out.JsSource
		*out = new(JavaScriptSource)
		(*in).DeepCopyInto(*out)
	}
	if in.WasmSource != nil {
		in, out := &in.WasmSource, &out.WasmSource
		*out = new(WasmSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeFunctionCodeSource.
func (in *EdgeFunctionCodeSource) DeepCopy() *EdgeFunctionCodeSource {
	if in == nil {
		return nil
	}
	out := new(EdgeFunctionCodeSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeFunctionList) DeepCopyInto(out *EdgeFunctionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EdgeFunction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeFunctionList.
func (in *EdgeFunctionList) DeepCopy() *EdgeFunctionList {
	if in == nil {
		return nil
	}
	out := new(EdgeFunctionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EdgeFunctionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeFunctionRevision) DeepCopyInto(out *EdgeFunctionRevision) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeFunctionRevision.
func (in *EdgeFunctionRevision) DeepCopy() *EdgeFunctionRevision {
	if in == nil {
		return nil
	}
	out := new(EdgeFunctionRevision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeFunctionSpec) DeepCopyInto(out *EdgeFunctionSpec) {
	*out = *in
	in.Code.DeepCopyInto(&out.Code)
	out.Env = in.Env
	in.RuntimeConfig.DeepCopyInto(&out.RuntimeConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeFunctionSpec.
func (in *EdgeFunctionSpec) DeepCopy() *EdgeFunctionSpec {
	if in == nil {
		return nil
	}
	out := new(EdgeFunctionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeFunctionStatus) DeepCopyInto(out *EdgeFunctionStatus) {
	*out = *in
	if in.Revisions != nil {
		in, out := &in.Revisions, &out.Revisions
		*out = make([]EdgeFunctionRevision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeFunctionStatus.
func (in *EdgeFunctionStatus) DeepCopy() *EdgeFunctionStatus {
	if in == nil {
		return nil
	}
	out := new(EdgeFunctionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvVar.
func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaScriptAssetsSource) DeepCopyInto(out *JavaScriptAssetsSource) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]SourceFile, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaScriptAssetsSource.
func (in *JavaScriptAssetsSource) DeepCopy() *JavaScriptAssetsSource {
	if in == nil {
		return nil
	}
	out := new(JavaScriptAssetsSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaScriptGitSource) DeepCopyInto(out *JavaScriptGitSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaScriptGitSource.
func (in *JavaScriptGitSource) DeepCopy() *JavaScriptGitSource {
	if in == nil {
		return nil
	}
	out := new(JavaScriptGitSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaScriptNpmSource) DeepCopyInto(out *JavaScriptNpmSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaScriptNpmSource.
func (in *JavaScriptNpmSource) DeepCopy() *JavaScriptNpmSource {
	if in == nil {
		return nil
	}
	out := new(JavaScriptNpmSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaScriptSource) DeepCopyInto(out *JavaScriptSource) {
	*out = *in
	if in.Assets != nil {
		in, out := &in.Assets, &out.Assets
		*out = new(JavaScriptAssetsSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(JavaScriptGitSource)
		**out = **in
	}
	if in.Npm != nil {
		in, out := &in.Npm, &out.Npm
		*out = new(JavaScriptNpmSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaScriptSource.
func (in *JavaScriptSource) DeepCopy() *JavaScriptSource {
	if in == nil {
		return nil
	}
	out := new(JavaScriptSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeCapability) DeepCopyInto(out *RuntimeCapability) {
	*out = *in
	if in.FetchAPI != nil {
		in, out := &in.FetchAPI, &out.FetchAPI
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeCapability.
func (in *RuntimeCapability) DeepCopy() *RuntimeCapability {
	if in == nil {
		return nil
	}
	out := new(RuntimeCapability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuntimeConfig) DeepCopyInto(out *RuntimeConfig) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]RuntimeCapability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuntimeConfig.
func (in *RuntimeConfig) DeepCopy() *RuntimeConfig {
	if in == nil {
		return nil
	}
	out := new(RuntimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceFile) DeepCopyInto(out *SourceFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceFile.
func (in *SourceFile) DeepCopy() *SourceFile {
	if in == nil {
		return nil
	}
	out := new(SourceFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WasmSource) DeepCopyInto(out *WasmSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WasmSource.
func (in *WasmSource) DeepCopy() *WasmSource {
	if in == nil {
		return nil
	}
	out := new(WasmSource)
	in.DeepCopyInto(out)
	return out
}
