// Code generated by client-gen. DO NOT EDIT.

package v1

type GRPCRouteExpansion interface{}

type GatewayExpansion interface{}

type GatewayClassExpansion interface{}

type HTTPRouteExpansion interface{}
