// Code generated by lister-gen. DO NOT EDIT.

package v1

// GRPCRouteListerExpansion allows custom methods to be added to
// GRPCRouteLister.
type GRPCRouteListerExpansion interface{}

// GatewayListerExpansion allows custom methods to be added to
// GatewayLister.
type GatewayListerExpansion interface{}

// GatewayClassListerExpansion allows custom methods to be added to
// GatewayClassLister.
type GatewayClassListerExpansion interface{}

// HTTPRouteListerExpansion allows custom methods to be added to
// HTTPRouteLister.
type HTTPRouteListerExpansion interface{}
