// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/apoxy-dev/apoxy-cli/api/gateway/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GRPCRouteLister helps list GRPCRoutes.
// All objects returned here must be treated as read-only.
type GRPCRouteLister interface {
	// List lists all GRPCRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.GRPCRoute, err error)
	// Get retrieves the GRPCRoute from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.GRPCRoute, error)
	GRPCRouteListerExpansion
}

// gRPCRouteLister implements the GRPCRouteLister interface.
type gRPCRouteLister struct {
	indexer cache.Indexer
}

// NewGRPCRouteLister returns a new GRPCRouteLister.
func NewGRPCRouteLister(indexer cache.Indexer) GRPCRouteLister {
	return &gRPCRouteLister{indexer: indexer}
}

// List lists all GRPCRoutes in the indexer.
func (s *gRPCRouteLister) List(selector labels.Selector) (ret []*v1.GRPCRoute, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.GRPCRoute))
	})
	return ret, err
}

// Get retrieves the GRPCRoute from the index for a given name.
func (s *gRPCRouteLister) Get(name string) (*v1.GRPCRoute, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("grpcroute"), name)
	}
	return obj.(*v1.GRPCRoute), nil
}
