// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/apoxy-dev/apoxy-cli/api/gateway/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HTTPRouteLister helps list HTTPRoutes.
// All objects returned here must be treated as read-only.
type HTTPRouteLister interface {
	// List lists all HTTPRoutes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.HTTPRoute, err error)
	// Get retrieves the HTTPRoute from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.HTTPRoute, error)
	HTTPRouteListerExpansion
}

// hTTPRouteLister implements the HTTPRouteLister interface.
type hTTPRouteLister struct {
	indexer cache.Indexer
}

// NewHTTPRouteLister returns a new HTTPRouteLister.
func NewHTTPRouteLister(indexer cache.Indexer) HTTPRouteLister {
	return &hTTPRouteLister{indexer: indexer}
}

// List lists all HTTPRoutes in the indexer.
func (s *hTTPRouteLister) List(selector labels.Selector) (ret []*v1.HTTPRoute, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.HTTPRoute))
	})
	return ret, err
}

// Get retrieves the HTTPRoute from the index for a given name.
func (s *hTTPRouteLister) Get(name string) (*v1.HTTPRoute, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("httproute"), name)
	}
	return obj.(*v1.HTTPRoute), nil
}
