/*
Copyright 2025 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha

import (
	internalinterfaces "github.com/apoxy-dev/apoxy/client/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Addresses returns a AddressInformer.
	Addresses() AddressInformer
	// Backends returns a BackendInformer.
	Backends() BackendInformer
	// Domains returns a DomainInformer.
	Domains() DomainInformer
	// DomainZones returns a DomainZoneInformer.
	DomainZones() DomainZoneInformer
	// Proxies returns a ProxyInformer.
	Proxies() ProxyInformer
	// TunnelNodes returns a TunnelNodeInformer.
	TunnelNodes() TunnelNodeInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Addresses returns a AddressInformer.
func (v *version) Addresses() AddressInformer {
	return &addressInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Backends returns a BackendInformer.
func (v *version) Backends() BackendInformer {
	return &backendInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Domains returns a DomainInformer.
func (v *version) Domains() DomainInformer {
	return &domainInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// DomainZones returns a DomainZoneInformer.
func (v *version) DomainZones() DomainZoneInformer {
	return &domainZoneInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Proxies returns a ProxyInformer.
func (v *version) Proxies() ProxyInformer {
	return &proxyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TunnelNodes returns a TunnelNodeInformer.
func (v *version) TunnelNodes() TunnelNodeInformer {
	return &tunnelNodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
