// Code generated by informer-gen. DO NOT EDIT.

package v1alpha

import (
	internalinterfaces "github.com/apoxy-dev/apoxy-cli/client/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Addresses returns a AddressInformer.
	Addresses() AddressInformer
	// Domains returns a DomainInformer.
	Domains() DomainInformer
	// Proxies returns a ProxyInformer.
	Proxies() ProxyInformer
	// TunnelNodes returns a TunnelNodeInformer.
	TunnelNodes() TunnelNodeInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Addresses returns a AddressInformer.
func (v *version) Addresses() AddressInformer {
	return &addressInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Domains returns a DomainInformer.
func (v *version) Domains() DomainInformer {
	return &domainInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Proxies returns a ProxyInformer.
func (v *version) Proxies() ProxyInformer {
	return &proxyInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// TunnelNodes returns a TunnelNodeInformer.
func (v *version) TunnelNodes() TunnelNodeInformer {
	return &tunnelNodeInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
