// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/apoxy-dev/apoxy-cli/client/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// GRPCRoutes returns a GRPCRouteInformer.
	GRPCRoutes() GRPCRouteInformer
	// Gateways returns a GatewayInformer.
	Gateways() GatewayInformer
	// GatewayClasses returns a GatewayClassInformer.
	GatewayClasses() GatewayClassInformer
	// HTTPRoutes returns a HTTPRouteInformer.
	HTTPRoutes() HTTPRouteInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// GRPCRoutes returns a GRPCRouteInformer.
func (v *version) GRPCRoutes() GRPCRouteInformer {
	return &gRPCRouteInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Gateways returns a GatewayInformer.
func (v *version) Gateways() GatewayInformer {
	return &gatewayInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// GatewayClasses returns a GatewayClassInformer.
func (v *version) GatewayClasses() GatewayClassInformer {
	return &gatewayClassInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// HTTPRoutes returns a HTTPRouteInformer.
func (v *version) HTTPRoutes() HTTPRouteInformer {
	return &hTTPRouteInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
