/*
Copyright 2025 Apoxy, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha "github.com/apoxy-dev/apoxy-cli/api/core/v1alpha"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTunnelPeerOffers implements TunnelPeerOfferInterface
type FakeTunnelPeerOffers struct {
	Fake *FakeCoreV1alpha
}

var tunnelpeeroffersResource = v1alpha.SchemeGroupVersion.WithResource("tunnelpeeroffers")

var tunnelpeeroffersKind = v1alpha.SchemeGroupVersion.WithKind("TunnelPeerOffer")

// Get takes name of the tunnelPeerOffer, and returns the corresponding tunnelPeerOffer object, and an error if there is any.
func (c *FakeTunnelPeerOffers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha.TunnelPeerOffer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(tunnelpeeroffersResource, name), &v1alpha.TunnelPeerOffer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.TunnelPeerOffer), err
}

// List takes label and field selectors, and returns the list of TunnelPeerOffers that match those selectors.
func (c *FakeTunnelPeerOffers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha.TunnelPeerOfferList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(tunnelpeeroffersResource, tunnelpeeroffersKind, opts), &v1alpha.TunnelPeerOfferList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha.TunnelPeerOfferList{ListMeta: obj.(*v1alpha.TunnelPeerOfferList).ListMeta}
	for _, item := range obj.(*v1alpha.TunnelPeerOfferList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tunnelPeerOffers.
func (c *FakeTunnelPeerOffers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(tunnelpeeroffersResource, opts))
}

// Create takes the representation of a tunnelPeerOffer and creates it.  Returns the server's representation of the tunnelPeerOffer, and an error, if there is any.
func (c *FakeTunnelPeerOffers) Create(ctx context.Context, tunnelPeerOffer *v1alpha.TunnelPeerOffer, opts v1.CreateOptions) (result *v1alpha.TunnelPeerOffer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(tunnelpeeroffersResource, tunnelPeerOffer), &v1alpha.TunnelPeerOffer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.TunnelPeerOffer), err
}

// Update takes the representation of a tunnelPeerOffer and updates it. Returns the server's representation of the tunnelPeerOffer, and an error, if there is any.
func (c *FakeTunnelPeerOffers) Update(ctx context.Context, tunnelPeerOffer *v1alpha.TunnelPeerOffer, opts v1.UpdateOptions) (result *v1alpha.TunnelPeerOffer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(tunnelpeeroffersResource, tunnelPeerOffer), &v1alpha.TunnelPeerOffer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.TunnelPeerOffer), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTunnelPeerOffers) UpdateStatus(ctx context.Context, tunnelPeerOffer *v1alpha.TunnelPeerOffer, opts v1.UpdateOptions) (*v1alpha.TunnelPeerOffer, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(tunnelpeeroffersResource, "status", tunnelPeerOffer), &v1alpha.TunnelPeerOffer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.TunnelPeerOffer), err
}

// Delete takes name of the tunnelPeerOffer and deletes it. Returns an error if one occurs.
func (c *FakeTunnelPeerOffers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(tunnelpeeroffersResource, name, opts), &v1alpha.TunnelPeerOffer{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTunnelPeerOffers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(tunnelpeeroffersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha.TunnelPeerOfferList{})
	return err
}

// Patch applies the patch and returns the patched tunnelPeerOffer.
func (c *FakeTunnelPeerOffers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha.TunnelPeerOffer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(tunnelpeeroffersResource, name, pt, data, subresources...), &v1alpha.TunnelPeerOffer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha.TunnelPeerOffer), err
}
