// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha "github.com/apoxy-dev/apoxy-cli/client/versioned/typed/core/v1alpha"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCoreV1alpha struct {
	*testing.Fake
}

func (c *FakeCoreV1alpha) Addresses() v1alpha.AddressInterface {
	return &FakeAddresses{c}
}

func (c *FakeCoreV1alpha) Backends() v1alpha.BackendInterface {
	return &FakeBackends{c}
}

func (c *FakeCoreV1alpha) Domains() v1alpha.DomainInterface {
	return &FakeDomains{c}
}

func (c *FakeCoreV1alpha) Proxies() v1alpha.ProxyInterface {
	return &FakeProxies{c}
}

func (c *FakeCoreV1alpha) TunnelNodes() v1alpha.TunnelNodeInterface {
	return &FakeTunnelNodes{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCoreV1alpha) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
