// Code generated by client-gen. DO NOT EDIT.

package v1alpha

type AddressExpansion interface{}

type BackendExpansion interface{}

type DomainExpansion interface{}

type ProxyExpansion interface{}

type TunnelNodeExpansion interface{}
