// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/apoxy-dev/apoxy-cli/client/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// EdgeFunctions returns a EdgeFunctionInformer.
	EdgeFunctions() EdgeFunctionInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// EdgeFunctions returns a EdgeFunctionInformer.
func (v *version) EdgeFunctions() EdgeFunctionInformer {
	return &edgeFunctionInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
