// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// EdgeFunctionListerExpansion allows custom methods to be added to
// EdgeFunctionLister.
type EdgeFunctionListerExpansion interface{}
